### ISSUE TITLE
[Allowance Module] Allow to self destruct

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-modules#15]
In case of a big vulnerability having a `selfdestruct` (only callable by the deployer) would allow us to prevent all users to update their Safes.

Worst case scenario would be that our private key is stolen and the thief calls `selfdestruct`. That should never happen and should not be very bad either, users will lose access to the allowance feature. Another one is deployed and the Safes are configured again with the new module address.

**Comment by rmeissner** [comment]
It was decided not to implement this, as Gnosis doesn't want to hold ownership of any contract
